# Generated by Django 3.0.7 on 2020-07-10 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0005_auto_20200709_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='img',
            field=models.ImageField(default=True, upload_to='pics'),
            preserve_default=False,
        ),
    ]
